### ISSUE TITLE
Distribution not matching with scipy

### ISSUE THREAD

**Issue by pakphump** [gpitt71/gemact-code#1]
the pdf of distribution not equal to scipy distribution

for example 
Burr distribution with 

{'c': 3.120105438478298,
 'd': 1.8614197750694768,
 'loc': -1.3885523888984292,
 'scale': 837.6048494583347}
 
 has pdf not same with scipy.stats.burr

**Comment by EdoLu** [comment]
Hello, sorry for the late reply.
I do not see any discrepancy if I compare our Burr12 implementation with scipy one. Please be aware that you should refer to scipy burr12 (Burr Type XII) distribution ([https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.burr12.html#scipy.stats.burr12](url)) and not to scipy burr (Burr Type III) distribution. 
Let me know if your calculation works after this adjustment.
