### ISSUE TITLE
Installation infrastructure into Git, Nightly builds and more

### ISSUE THREAD

**Issue by Friedrich2** [gpitt71/gemact-code#2]
First: Thanks for the great work!

Second: The docs fit the Github version, but not the version distributed via pip. This is completely o. k. and acceptable. An easy installation process for the developer version for the uninitiated would be nice to be able to follow the Jupyter notebooks.
Simply installing via the Github repository did not work:
```
pip install --pre git+https://github.com/gpitt71/gemact-code.git
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/gpitt71/gemact-code.git
  Cloning https://github.com/gpitt71/gemact-code.git to c:\users\peter.jung\appdata\local\temp\pip-req-build-3n08yg0o
  Running command git clone --filter=blob:none --quiet https://github.com/gpitt71/gemact-code.git 'C:\Users\peter.jung\AppData\Local\Temp\pip-req-build-3n08yg0o'
  Resolved https://github.com/gpitt71/gemact-code.git to commit ec6a080c5e758af29214906b81677bda4a5e856e
ERROR: git+https://github.com/gpitt71/gemact-code.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
Could you

- include a valid pyproject.toml into the repository and / or
- give installation instructions for the developer version within the Readme or
- produce daily "Nightly builds", i. e. every day a newly packed Python package, which was automatically packed via Github automatical releases, e.g. via [this one](https://github.com/marketplace/actions/automatic-releases)?

**Comment by gpitt71** [comment]
Thank you very much for your feedback.

You should now be able to install the GitHub version of **gemact** using the command:

`pip install git+https://github.com/gpitt71/gemact-code.git`

Be aware that there could be ongoing changes in the GitHub version with respect to the version we released on PyPI. 
We will soon release a new version of the package that will be stable with respect to the current GitHub version,

Let me know if this helped!

**Comment by Friedrich2** [comment]
Many thanks, it works and helped! Nice to know: The uninstallation works too. (I re-installed it 1x to test this.)

**Comment by gpitt71** [comment]
Thank you again for your feedback, it was very helpufull to us.

I will close this issue
