### ISSUE TITLE
Tutorial links are not working

### ISSUE THREAD

**Issue by nsankar** [gpitt71/gemact-code#6]
@gpitt71 Hi. The following tutorial links are not working. Not linked properly.

"""
Click [here](https://github.com/gpitt71/gemact-code/blob/main/vignette/lossmodel.ipynb) to understand how to price (re)insurance contracts.

Click [here](https://github.com/gpitt71/gemact-code/blob/main/vignette/lossaggregation.ipynb) to understand how to perform risks aggregation.

Click [here](https://github.com/gpitt71/gemact-code/blob/main/vignette/distributions.ipynb) to understand how to use the distributions supported.

Click [here](https://github.com/gpitt71/gemact-code/blob/main/vignette/copulas.ipynb) to understand how to use the copula functions supported.

Click [here](https://github.com/gpitt71/gemact-code/blob/main/vignette/lossreserve.ipynb) to understand how to compute loss reserves.

"""

**Comment by gpitt71** [comment]
Hi @nsankar, thank you very much for your feedback. 

I have just fixed the issue. 

Please observe that the tutorials are referred to the version 0.3.1 of GEMAct. In the next days we will update the repository with the tutorials of the version 1.0.1 of GEMAct.

**Comment by nsankar** [comment]
Thanks for the quick fix and the info @gpitt71
